controller_manager:
  ros__parameters:
    update_rate: 30
    use_sim_time: false

    # The manager needs to know WHAT these are before it can load them
    mecanum_drive_controller:
      type: mecanum_drive_controller/MecanumDriveController

    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster

mecanum_drive_controller:
  ros__parameters:
    front_left_wheel_command_joint_name: "front_left_wheel_joint"
    front_right_wheel_command_joint_name: "front_right_wheel_joint"
    rear_left_wheel_command_joint_name: "rear_left_wheel_joint"
    rear_right_wheel_command_joint_name: "rear_right_wheel_joint"
    
    # Use 'reference_unstamped' for standard Twist from /cmd_vel
    use_stamped_vel: false 
    open_loop: true
    enable_odom_tf: true
    base_frame_id: "base_link"
    odom_frame_id: "odom"
    publish_rate: 50.0

    kinematics:
      wheel_separation_x: 0.175
      wheel_separation_y: 0.175
      wheels_radius: 0.05