/**:
  ros__parameters:
    type: "mecanum_drive_controller/MecanumDriveController"
    front_left_wheel_command_joint_name: "front_left_wheel_joint"
    front_right_wheel_command_joint_name: "front_right_wheel_joint"
    rear_left_wheel_command_joint_name: "rear_left_wheel_joint"
    rear_right_wheel_command_joint_name: "rear_right_wheel_joint"
    publish_rate: 50.0
    open_loop: false
    enable_odom_tf: true
    base_frame_id: "base_link"
    odom_frame_id: "odom"
    kinematics: # NEW: Add kinematics namespace
      wheel_separation_x: 0.175
      wheel_separation_y: 0.175
      wheel_radius: 0.05
    command_interfaces:
      - front_left_wheel_joint/velocity
      - front_right_wheel_joint/velocity
      - rear_left_wheel_joint/velocity
      - rear_right_wheel_joint/velocity