controller_manager:
  ros__parameters:
    update_rate: 100 # Hz

    mecanum_drive_controller:
      type: mecanum_drive_controller/MecanumDriveController

    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster

mecanum_drive_controller:
  ros__parameters:
    type: mecanum_drive_controller/MecanumDriveController
    front_left_wheel_command_joint_name: "front_left_wheel_joint"
    front_right_wheel_command_joint_name: "front_right_wheel_joint"
    rear_left_wheel_command_joint_name: "rear_left_wheel_joint"
    rear_right_wheel_command_joint_name: "rear_right_wheel_joint"
    publish_rate: 50.0
    open_loop: false
    enable_odom_tf: true
    base_frame_id: "base_link"
    odom_frame_id: "odom"
    kinematics:
      wheel_separation_x: 0.175
      wheel_separation_y: 0.175
      wheels_radius: 0.05
    command_interfaces:
      - velocity
    state_interfaces:
      - position
      - velocity

joint_broad:
  ros__parameters:
    type: joint_state_broadcaster/JointStateBroadcaster

/**:
  ros__parameters:
    use_sim_time: false
